version: '3.8'

services:
  api:
    build: .
    container_name: lsm-web-recorder-api
    restart: always
    ports:
      - "5000:5000" # Puerto del backend
    networks:
      - glowel_net
    environment:
      # Variables de entorno (valores se definen en Portainer)
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  glowel_net:
    external: true
